services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.dev
    image: mpjovanovich/raffle-tracker-api:dev
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      ## Bind mounts for local development; just point to local files
      - ./node_modules:/app/node_modules
      - ./api/data:/app/api/data
      - ./api/src:/app/api/src
      - ./auth:/app/auth
      - ./config:/app/config
      - ./dto:/app/dto

  web:
    build:
      context: .
      dockerfile: web/Dockerfile.dev
    image: mpjovanovich/raffle-tracker-web:dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./web/src:/app/web/src
      - ./config:/app/config
      - ./dto:/app/dto
      - ./auth:/app/auth
      - ./node_modules:/app/node_modules

  # password = admin
  # database = /data/raffle.db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=pepa-linha
    volumes:
      - ./api/data:/data
      - ./api/adminer_plugins:/var/www/html/plugins-enabled
