services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.dev
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - db_data:/app/api/data
      - ./api/src:/app/api/src
      - ./node_modules:/app/node_modules

  web:
    build:
      context: .
      dockerfile: web/Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./web/src:/app/web/src
      - ./node_modules:/app/node_modules

volumes:
  db_data:
    driver: local
