services:
  api:
    image: ghcr.io/mpjovanovich/raffle-tracker-api:latest
    expose:
      - '3001'
    env_file:
      - .env
    volumes:
      - db_data:/app/api/data

  web:
    image: ghcr.io/mpjovanovich/raffle-tracker-web:latest
    expose:
      - '3000'
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    depends_on:
      - web
      - api
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

volumes:
  db_data:
    driver: local
