services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: api/Dockerfile.prod
  #   ports:
  #     - '3001:3001'
  #   env_file:
  #     - .env.prod
  #   volumes:
  #     - db_data:/app/api/data

  web:
    build:
      context: .
      dockerfile: web/Dockerfile.prod
      args:
        - API_PORT=${API_PORT}
        - API_BASE_URL=${API_BASE_URL}
        - CORS_ORIGIN=${CORS_ORIGIN}
        - EMAIL_FROM=${EMAIL_FROM}
        - EMAIL_USER=${EMAIL_USER}
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        - EMAIL_PROVIDER=${EMAIL_PROVIDER}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}
        - LOG_DIR=${LOG_DIR}
        - HACKED_NODE_ENV_BECAUSE_NEXT_JS_HAS_TOO_MANY_RULES=${HACKED_NODE_ENV_BECAUSE_NEXT_JS_HAS_TOO_MANY_RULES}
        - WEB_BASE_URL=${WEB_BASE_URL}
        - WEB_PORT=${WEB_PORT}
    ports:
      - '3000:3000'
    env_file:
      - .env.prod

volumes:
  db_data:
    driver: local
