services:
  api:
    image: ghcr.io/mpjovanovich/raffle-tracker-api:latest
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - db_data:/app/api/data

  web:
    image: ghcr.io/mpjovanovich/raffle-tracker-web:latest
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  db_data:
    driver: local
