services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.dev
    image: mpjovanovich/raffle-tracker-api:dev
    expose:
      - 3001
    env_file:
      - .env
    volumes:
      ## Bind mounts for local development; just point to local files
      - ./api/data:/app/api/data
      - ./api/src:/app/api/src
      - ./config:/app/config
      - ./dto:/app/dto
      - ./auth:/app/auth
      - ./node_modules:/app/node_modules

  web:
    build:
      context: .
      dockerfile: web/Dockerfile.dev
    image: mpjovanovich/raffle-tracker-web:dev
    expose:
      - 3000
    env_file:
      - .env
    volumes:
      - ./web/src:/app/web/src
      - ./config:/app/config
      - ./dto:/app/dto
      - ./auth:/app/auth
      - ./node_modules:/app/node_modules

  nginx:
    image: nginx:alpine
    depends_on:
      - web
      - api
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
