# Use this to bring up supporting services for local development.

# Need to run these in shell before running docker-compose up
# export MY_UID=$(id -u)
# export MY_GID=$(id -g)

# Adminer:
# password = admin
# database = /data/raffle.db

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DESIGN=pepa-linha
    volumes:
      - ./api/data:/data
      - ./api/adminer_plugins:/var/www/html/plugins-enabled
    user: '${MY_UID}:${MY_GID}'
