services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.dev
    ports:
      - '3001:3001'
    env_file:
      - .env
    # Not needed for prod
    develop:
      watch:
        - action: sync
          path: ./api/src
          target: /app/api/src
          ignore:
            - node_modules/
