services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.build
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - db_data:/app/api/data
    image: mpjovanovich/raffle-tracker-api:latest

  web:
    build:
      context: .
      dockerfile: web/Dockerfile.build
    ports:
      - '3000:3000'
    env_file:
      - .env
    image: mpjovanovich/raffle-tracker-web:latest

volumes:
  db_data:
    driver: local
