services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.prod
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - db_data:/app/api/data

  # web:
  #   build:
  #     context: .
  #     dockerfile: web/Dockerfile.dev
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - .env

volumes:
  db_data:
    driver: local
