# Start with node base image
FROM node:22-alpine

# Install sqlite3
RUN apk add --no-cache sqlite

# Go to the src
WORKDIR /app

# Copy all of the package.json files needed
COPY package*.json ./

# Install dependencies (no source code at this point)
RUN npm ci

# Copy all source code (that's not in docker igore) to the container.
# Just copy everything for now. We can be more selective later.
COPY . .

# Generate workspace symlinks after copying source
RUN npm install --workspaces

# Generate Prisma objects inside of the docker volume
RUN npm run prisma:generate --workspace api
RUN npm run prisma:push --workspace api
RUN npm run db:seed-test --workspace api

# Expose port
EXPOSE 3001

# Switch to api dir
WORKDIR /app/api

# Start the application
CMD ["npm", "run", "dev"]