# Start with node base image
FROM node:22-alpine

# Go to the src
WORKDIR /app

# Copy all of the package.json files needed
COPY package*.json ./
COPY api/package*.json ./api/
COPY dto/package*.json ./dto/

# Install dependencies (no source code at this point)
RUN npm ci

# Copy all source code (that's not in docker igore) to the container.
# Just copy everything for now. We can be more selective later.
COPY . .

# Generate workspace symlinks after copying source
RUN npm install --workspaces


# Build the app
RUN npm run build --workspace=config
RUN npm run build --workspace=dto
RUN npm run build --workspace=auth
RUN npm run build --workspace=api

# Generate Prisma objects
RUN npm run prisma:generate --workspace api
RUN npm run prisma:push --workspace api

# Expose port
EXPOSE 3001

# Switch to api dir
WORKDIR /app/api

# Start the application
CMD ["npm", "start"]
